// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarStyle
{
	DefaultStyle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Default (dark text on iOS, light text on Android)" }, new java.lang.String[] { "pt_BR", "Default (dark text on iOS, light text on Android)" } }),
	LightContentStyle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Light text" }, new java.lang.String[] { "pt_BR", "Light text" } }),
	DarkContentStyle(new java.lang.String[][] { new java.lang.String[] { "en_US", "Dark text" }, new java.lang.String[] { "pt_BR", "Dark text" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private StatusBarStyle(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "pt_BR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("pt_BR");
	}
}
