// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class Diagnostico_de_implementacao implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject diagnostico_de_implementacaoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.Diagnostico_de_implementacao";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Assentamento("Assentamento"),
		Assentado("Assentado"),
		Tecnico("Tecnico"),
		Comunidade("Comunidade"),
		Ano_do_talhao("Ano_do_talhao"),
		Praga("Praga"),
		ocorrencia_florestal("ocorrencia_florestal");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Diagnostico_de_implementacao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Diagnostico_de_implementacao(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject diagnostico_de_implementacaoMendixObject)
	{
		if (diagnostico_de_implementacaoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, diagnostico_de_implementacaoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.diagnostico_de_implementacaoMendixObject = diagnostico_de_implementacaoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.Diagnostico_de_implementacao initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.Diagnostico_de_implementacao(context, mendixObject);
	}

	public static nativemobile.proxies.Diagnostico_de_implementacao load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.Diagnostico_de_implementacao.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.Diagnostico_de_implementacao> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativemobile.proxies.Diagnostico_de_implementacao.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Assentamento
	 */
	public final java.lang.String getAssentamento()
	{
		return getAssentamento(getContext());
	}

	/**
	 * @param context
	 * @return value of Assentamento
	 */
	public final java.lang.String getAssentamento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assentamento.toString());
	}

	/**
	 * Set value of Assentamento
	 * @param assentamento
	 */
	public final void setAssentamento(java.lang.String assentamento)
	{
		setAssentamento(getContext(), assentamento);
	}

	/**
	 * Set value of Assentamento
	 * @param context
	 * @param assentamento
	 */
	public final void setAssentamento(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assentamento)
	{
		getMendixObject().setValue(context, MemberNames.Assentamento.toString(), assentamento);
	}

	/**
	 * @return value of Assentado
	 */
	public final java.lang.String getAssentado()
	{
		return getAssentado(getContext());
	}

	/**
	 * @param context
	 * @return value of Assentado
	 */
	public final java.lang.String getAssentado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assentado.toString());
	}

	/**
	 * Set value of Assentado
	 * @param assentado
	 */
	public final void setAssentado(java.lang.String assentado)
	{
		setAssentado(getContext(), assentado);
	}

	/**
	 * Set value of Assentado
	 * @param context
	 * @param assentado
	 */
	public final void setAssentado(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assentado)
	{
		getMendixObject().setValue(context, MemberNames.Assentado.toString(), assentado);
	}

	/**
	 * @return value of Tecnico
	 */
	public final java.lang.String getTecnico()
	{
		return getTecnico(getContext());
	}

	/**
	 * @param context
	 * @return value of Tecnico
	 */
	public final java.lang.String getTecnico(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tecnico.toString());
	}

	/**
	 * Set value of Tecnico
	 * @param tecnico
	 */
	public final void setTecnico(java.lang.String tecnico)
	{
		setTecnico(getContext(), tecnico);
	}

	/**
	 * Set value of Tecnico
	 * @param context
	 * @param tecnico
	 */
	public final void setTecnico(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tecnico)
	{
		getMendixObject().setValue(context, MemberNames.Tecnico.toString(), tecnico);
	}

	/**
	 * @return value of Comunidade
	 */
	public final java.lang.String getComunidade()
	{
		return getComunidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Comunidade
	 */
	public final java.lang.String getComunidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comunidade.toString());
	}

	/**
	 * Set value of Comunidade
	 * @param comunidade
	 */
	public final void setComunidade(java.lang.String comunidade)
	{
		setComunidade(getContext(), comunidade);
	}

	/**
	 * Set value of Comunidade
	 * @param context
	 * @param comunidade
	 */
	public final void setComunidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comunidade)
	{
		getMendixObject().setValue(context, MemberNames.Comunidade.toString(), comunidade);
	}

	/**
	 * @return value of Ano_do_talhao
	 */
	public final java.lang.Integer getAno_do_talhao()
	{
		return getAno_do_talhao(getContext());
	}

	/**
	 * @param context
	 * @return value of Ano_do_talhao
	 */
	public final java.lang.Integer getAno_do_talhao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ano_do_talhao.toString());
	}

	/**
	 * Set value of Ano_do_talhao
	 * @param ano_do_talhao
	 */
	public final void setAno_do_talhao(java.lang.Integer ano_do_talhao)
	{
		setAno_do_talhao(getContext(), ano_do_talhao);
	}

	/**
	 * Set value of Ano_do_talhao
	 * @param context
	 * @param ano_do_talhao
	 */
	public final void setAno_do_talhao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ano_do_talhao)
	{
		getMendixObject().setValue(context, MemberNames.Ano_do_talhao.toString(), ano_do_talhao);
	}

	/**
	 * @return value of Praga
	 */
	public final java.lang.Boolean getPraga()
	{
		return getPraga(getContext());
	}

	/**
	 * @param context
	 * @return value of Praga
	 */
	public final java.lang.Boolean getPraga(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Praga.toString());
	}

	/**
	 * Set value of Praga
	 * @param praga
	 */
	public final void setPraga(java.lang.Boolean praga)
	{
		setPraga(getContext(), praga);
	}

	/**
	 * Set value of Praga
	 * @param context
	 * @param praga
	 */
	public final void setPraga(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean praga)
	{
		getMendixObject().setValue(context, MemberNames.Praga.toString(), praga);
	}

	/**
	 * @return value of ocorrencia_florestal
	 */
	public final java.lang.Boolean getocorrencia_florestal()
	{
		return getocorrencia_florestal(getContext());
	}

	/**
	 * @param context
	 * @return value of ocorrencia_florestal
	 */
	public final java.lang.Boolean getocorrencia_florestal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ocorrencia_florestal.toString());
	}

	/**
	 * Set value of ocorrencia_florestal
	 * @param ocorrencia_florestal
	 */
	public final void setocorrencia_florestal(java.lang.Boolean ocorrencia_florestal)
	{
		setocorrencia_florestal(getContext(), ocorrencia_florestal);
	}

	/**
	 * Set value of ocorrencia_florestal
	 * @param context
	 * @param ocorrencia_florestal
	 */
	public final void setocorrencia_florestal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ocorrencia_florestal)
	{
		getMendixObject().setValue(context, MemberNames.ocorrencia_florestal.toString(), ocorrencia_florestal);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return diagnostico_de_implementacaoMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.Diagnostico_de_implementacao that = (nativemobile.proxies.Diagnostico_de_implementacao) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
