// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class Ficha_anual implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ficha_anualMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.Ficha_anual";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Assentamento("Assentamento"),
		Assentado("Assentado"),
		Comunidade("Comunidade"),
		lote("lote"),
		Ano_talhao("Ano_talhao"),
		Espacamento_do_cafe("Espacamento_do_cafe"),
		Municipio("Municipio"),
		CPF("CPF");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ficha_anual(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ficha_anual(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ficha_anualMendixObject)
	{
		if (ficha_anualMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, ficha_anualMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.ficha_anualMendixObject = ficha_anualMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.Ficha_anual initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.Ficha_anual(context, mendixObject);
	}

	public static nativemobile.proxies.Ficha_anual load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.Ficha_anual.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.Ficha_anual> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativemobile.proxies.Ficha_anual.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Assentamento
	 */
	public final java.lang.String getAssentamento()
	{
		return getAssentamento(getContext());
	}

	/**
	 * @param context
	 * @return value of Assentamento
	 */
	public final java.lang.String getAssentamento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assentamento.toString());
	}

	/**
	 * Set value of Assentamento
	 * @param assentamento
	 */
	public final void setAssentamento(java.lang.String assentamento)
	{
		setAssentamento(getContext(), assentamento);
	}

	/**
	 * Set value of Assentamento
	 * @param context
	 * @param assentamento
	 */
	public final void setAssentamento(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assentamento)
	{
		getMendixObject().setValue(context, MemberNames.Assentamento.toString(), assentamento);
	}

	/**
	 * @return value of Assentado
	 */
	public final java.lang.String getAssentado()
	{
		return getAssentado(getContext());
	}

	/**
	 * @param context
	 * @return value of Assentado
	 */
	public final java.lang.String getAssentado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assentado.toString());
	}

	/**
	 * Set value of Assentado
	 * @param assentado
	 */
	public final void setAssentado(java.lang.String assentado)
	{
		setAssentado(getContext(), assentado);
	}

	/**
	 * Set value of Assentado
	 * @param context
	 * @param assentado
	 */
	public final void setAssentado(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assentado)
	{
		getMendixObject().setValue(context, MemberNames.Assentado.toString(), assentado);
	}

	/**
	 * @return value of Comunidade
	 */
	public final java.lang.String getComunidade()
	{
		return getComunidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Comunidade
	 */
	public final java.lang.String getComunidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comunidade.toString());
	}

	/**
	 * Set value of Comunidade
	 * @param comunidade
	 */
	public final void setComunidade(java.lang.String comunidade)
	{
		setComunidade(getContext(), comunidade);
	}

	/**
	 * Set value of Comunidade
	 * @param context
	 * @param comunidade
	 */
	public final void setComunidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comunidade)
	{
		getMendixObject().setValue(context, MemberNames.Comunidade.toString(), comunidade);
	}

	/**
	 * @return value of lote
	 */
	public final java.lang.Integer getlote()
	{
		return getlote(getContext());
	}

	/**
	 * @param context
	 * @return value of lote
	 */
	public final java.lang.Integer getlote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.lote.toString());
	}

	/**
	 * Set value of lote
	 * @param lote
	 */
	public final void setlote(java.lang.Integer lote)
	{
		setlote(getContext(), lote);
	}

	/**
	 * Set value of lote
	 * @param context
	 * @param lote
	 */
	public final void setlote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer lote)
	{
		getMendixObject().setValue(context, MemberNames.lote.toString(), lote);
	}

	/**
	 * @return value of Ano_talhao
	 */
	public final java.lang.Integer getAno_talhao()
	{
		return getAno_talhao(getContext());
	}

	/**
	 * @param context
	 * @return value of Ano_talhao
	 */
	public final java.lang.Integer getAno_talhao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ano_talhao.toString());
	}

	/**
	 * Set value of Ano_talhao
	 * @param ano_talhao
	 */
	public final void setAno_talhao(java.lang.Integer ano_talhao)
	{
		setAno_talhao(getContext(), ano_talhao);
	}

	/**
	 * Set value of Ano_talhao
	 * @param context
	 * @param ano_talhao
	 */
	public final void setAno_talhao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ano_talhao)
	{
		getMendixObject().setValue(context, MemberNames.Ano_talhao.toString(), ano_talhao);
	}

	/**
	 * @return value of Espacamento_do_cafe
	 */
	public final java.math.BigDecimal getEspacamento_do_cafe()
	{
		return getEspacamento_do_cafe(getContext());
	}

	/**
	 * @param context
	 * @return value of Espacamento_do_cafe
	 */
	public final java.math.BigDecimal getEspacamento_do_cafe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Espacamento_do_cafe.toString());
	}

	/**
	 * Set value of Espacamento_do_cafe
	 * @param espacamento_do_cafe
	 */
	public final void setEspacamento_do_cafe(java.math.BigDecimal espacamento_do_cafe)
	{
		setEspacamento_do_cafe(getContext(), espacamento_do_cafe);
	}

	/**
	 * Set value of Espacamento_do_cafe
	 * @param context
	 * @param espacamento_do_cafe
	 */
	public final void setEspacamento_do_cafe(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal espacamento_do_cafe)
	{
		getMendixObject().setValue(context, MemberNames.Espacamento_do_cafe.toString(), espacamento_do_cafe);
	}

	/**
	 * @return value of Municipio
	 */
	public final java.lang.String getMunicipio()
	{
		return getMunicipio(getContext());
	}

	/**
	 * @param context
	 * @return value of Municipio
	 */
	public final java.lang.String getMunicipio(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Municipio.toString());
	}

	/**
	 * Set value of Municipio
	 * @param municipio
	 */
	public final void setMunicipio(java.lang.String municipio)
	{
		setMunicipio(getContext(), municipio);
	}

	/**
	 * Set value of Municipio
	 * @param context
	 * @param municipio
	 */
	public final void setMunicipio(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String municipio)
	{
		getMendixObject().setValue(context, MemberNames.Municipio.toString(), municipio);
	}

	/**
	 * @return value of CPF
	 */
	public final java.lang.String getCPF()
	{
		return getCPF(getContext());
	}

	/**
	 * @param context
	 * @return value of CPF
	 */
	public final java.lang.String getCPF(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CPF.toString());
	}

	/**
	 * Set value of CPF
	 * @param cpf
	 */
	public final void setCPF(java.lang.String cpf)
	{
		setCPF(getContext(), cpf);
	}

	/**
	 * Set value of CPF
	 * @param context
	 * @param cpf
	 */
	public final void setCPF(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cpf)
	{
		getMendixObject().setValue(context, MemberNames.CPF.toString(), cpf);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ficha_anualMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.Ficha_anual that = (nativemobile.proxies.Ficha_anual) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
