// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class Ficha_entrega_insumos implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ficha_entrega_insumosMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.Ficha_entrega_insumos";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Asentamento("Asentamento"),
		Asentado("Asentado"),
		Cafe("Cafe"),
		Replantio_Cafe("Replantio_Cafe"),
		florestais("florestais"),
		Anuais("Anuais"),
		Adubo("Adubo"),
		Calcario("Calcario");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ficha_entrega_insumos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ficha_entrega_insumos(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ficha_entrega_insumosMendixObject)
	{
		if (ficha_entrega_insumosMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, ficha_entrega_insumosMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.ficha_entrega_insumosMendixObject = ficha_entrega_insumosMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.Ficha_entrega_insumos initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.Ficha_entrega_insumos(context, mendixObject);
	}

	public static nativemobile.proxies.Ficha_entrega_insumos load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.Ficha_entrega_insumos.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.Ficha_entrega_insumos> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativemobile.proxies.Ficha_entrega_insumos.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Asentamento
	 */
	public final java.lang.String getAsentamento()
	{
		return getAsentamento(getContext());
	}

	/**
	 * @param context
	 * @return value of Asentamento
	 */
	public final java.lang.String getAsentamento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Asentamento.toString());
	}

	/**
	 * Set value of Asentamento
	 * @param asentamento
	 */
	public final void setAsentamento(java.lang.String asentamento)
	{
		setAsentamento(getContext(), asentamento);
	}

	/**
	 * Set value of Asentamento
	 * @param context
	 * @param asentamento
	 */
	public final void setAsentamento(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String asentamento)
	{
		getMendixObject().setValue(context, MemberNames.Asentamento.toString(), asentamento);
	}

	/**
	 * @return value of Asentado
	 */
	public final java.lang.String getAsentado()
	{
		return getAsentado(getContext());
	}

	/**
	 * @param context
	 * @return value of Asentado
	 */
	public final java.lang.String getAsentado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Asentado.toString());
	}

	/**
	 * Set value of Asentado
	 * @param asentado
	 */
	public final void setAsentado(java.lang.String asentado)
	{
		setAsentado(getContext(), asentado);
	}

	/**
	 * Set value of Asentado
	 * @param context
	 * @param asentado
	 */
	public final void setAsentado(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String asentado)
	{
		getMendixObject().setValue(context, MemberNames.Asentado.toString(), asentado);
	}

	/**
	 * @return value of Cafe
	 */
	public final java.lang.Integer getCafe()
	{
		return getCafe(getContext());
	}

	/**
	 * @param context
	 * @return value of Cafe
	 */
	public final java.lang.Integer getCafe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Cafe.toString());
	}

	/**
	 * Set value of Cafe
	 * @param cafe
	 */
	public final void setCafe(java.lang.Integer cafe)
	{
		setCafe(getContext(), cafe);
	}

	/**
	 * Set value of Cafe
	 * @param context
	 * @param cafe
	 */
	public final void setCafe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer cafe)
	{
		getMendixObject().setValue(context, MemberNames.Cafe.toString(), cafe);
	}

	/**
	 * @return value of Replantio_Cafe
	 */
	public final java.lang.Integer getReplantio_Cafe()
	{
		return getReplantio_Cafe(getContext());
	}

	/**
	 * @param context
	 * @return value of Replantio_Cafe
	 */
	public final java.lang.Integer getReplantio_Cafe(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Replantio_Cafe.toString());
	}

	/**
	 * Set value of Replantio_Cafe
	 * @param replantio_cafe
	 */
	public final void setReplantio_Cafe(java.lang.Integer replantio_cafe)
	{
		setReplantio_Cafe(getContext(), replantio_cafe);
	}

	/**
	 * Set value of Replantio_Cafe
	 * @param context
	 * @param replantio_cafe
	 */
	public final void setReplantio_Cafe(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer replantio_cafe)
	{
		getMendixObject().setValue(context, MemberNames.Replantio_Cafe.toString(), replantio_cafe);
	}

	/**
	 * @return value of florestais
	 */
	public final java.lang.Integer getflorestais()
	{
		return getflorestais(getContext());
	}

	/**
	 * @param context
	 * @return value of florestais
	 */
	public final java.lang.Integer getflorestais(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.florestais.toString());
	}

	/**
	 * Set value of florestais
	 * @param florestais
	 */
	public final void setflorestais(java.lang.Integer florestais)
	{
		setflorestais(getContext(), florestais);
	}

	/**
	 * Set value of florestais
	 * @param context
	 * @param florestais
	 */
	public final void setflorestais(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer florestais)
	{
		getMendixObject().setValue(context, MemberNames.florestais.toString(), florestais);
	}

	/**
	 * @return value of Anuais
	 */
	public final java.lang.Integer getAnuais()
	{
		return getAnuais(getContext());
	}

	/**
	 * @param context
	 * @return value of Anuais
	 */
	public final java.lang.Integer getAnuais(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Anuais.toString());
	}

	/**
	 * Set value of Anuais
	 * @param anuais
	 */
	public final void setAnuais(java.lang.Integer anuais)
	{
		setAnuais(getContext(), anuais);
	}

	/**
	 * Set value of Anuais
	 * @param context
	 * @param anuais
	 */
	public final void setAnuais(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer anuais)
	{
		getMendixObject().setValue(context, MemberNames.Anuais.toString(), anuais);
	}

	/**
	 * @return value of Adubo
	 */
	public final java.lang.String getAdubo()
	{
		return getAdubo(getContext());
	}

	/**
	 * @param context
	 * @return value of Adubo
	 */
	public final java.lang.String getAdubo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Adubo.toString());
	}

	/**
	 * Set value of Adubo
	 * @param adubo
	 */
	public final void setAdubo(java.lang.String adubo)
	{
		setAdubo(getContext(), adubo);
	}

	/**
	 * Set value of Adubo
	 * @param context
	 * @param adubo
	 */
	public final void setAdubo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adubo)
	{
		getMendixObject().setValue(context, MemberNames.Adubo.toString(), adubo);
	}

	/**
	 * @return value of Calcario
	 */
	public final java.lang.String getCalcario()
	{
		return getCalcario(getContext());
	}

	/**
	 * @param context
	 * @return value of Calcario
	 */
	public final java.lang.String getCalcario(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Calcario.toString());
	}

	/**
	 * Set value of Calcario
	 * @param calcario
	 */
	public final void setCalcario(java.lang.String calcario)
	{
		setCalcario(getContext(), calcario);
	}

	/**
	 * Set value of Calcario
	 * @param context
	 * @param calcario
	 */
	public final void setCalcario(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String calcario)
	{
		getMendixObject().setValue(context, MemberNames.Calcario.toString(), calcario);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ficha_entrega_insumosMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.Ficha_entrega_insumos that = (nativemobile.proxies.Ficha_entrega_insumos) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
