// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class Ficha_Mensal implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject ficha_MensalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.Ficha_Mensal";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Assentaento("Assentaento"),
		Assentado("Assentado"),
		Comunidade("Comunidade"),
		Ano_Talhao("Ano_Talhao"),
		Numero_talhao("Numero_talhao"),
		Orientacoes("Orientacoes"),
		Tipo("Tipo");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Ficha_Mensal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Ficha_Mensal(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject ficha_MensalMendixObject)
	{
		if (ficha_MensalMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, ficha_MensalMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.ficha_MensalMendixObject = ficha_MensalMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.Ficha_Mensal initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.Ficha_Mensal(context, mendixObject);
	}

	public static nativemobile.proxies.Ficha_Mensal load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.Ficha_Mensal.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.Ficha_Mensal> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativemobile.proxies.Ficha_Mensal.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Assentaento
	 */
	public final java.lang.String getAssentaento()
	{
		return getAssentaento(getContext());
	}

	/**
	 * @param context
	 * @return value of Assentaento
	 */
	public final java.lang.String getAssentaento(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assentaento.toString());
	}

	/**
	 * Set value of Assentaento
	 * @param assentaento
	 */
	public final void setAssentaento(java.lang.String assentaento)
	{
		setAssentaento(getContext(), assentaento);
	}

	/**
	 * Set value of Assentaento
	 * @param context
	 * @param assentaento
	 */
	public final void setAssentaento(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assentaento)
	{
		getMendixObject().setValue(context, MemberNames.Assentaento.toString(), assentaento);
	}

	/**
	 * @return value of Assentado
	 */
	public final java.lang.String getAssentado()
	{
		return getAssentado(getContext());
	}

	/**
	 * @param context
	 * @return value of Assentado
	 */
	public final java.lang.String getAssentado(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assentado.toString());
	}

	/**
	 * Set value of Assentado
	 * @param assentado
	 */
	public final void setAssentado(java.lang.String assentado)
	{
		setAssentado(getContext(), assentado);
	}

	/**
	 * Set value of Assentado
	 * @param context
	 * @param assentado
	 */
	public final void setAssentado(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assentado)
	{
		getMendixObject().setValue(context, MemberNames.Assentado.toString(), assentado);
	}

	/**
	 * @return value of Comunidade
	 */
	public final java.lang.String getComunidade()
	{
		return getComunidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Comunidade
	 */
	public final java.lang.String getComunidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Comunidade.toString());
	}

	/**
	 * Set value of Comunidade
	 * @param comunidade
	 */
	public final void setComunidade(java.lang.String comunidade)
	{
		setComunidade(getContext(), comunidade);
	}

	/**
	 * Set value of Comunidade
	 * @param context
	 * @param comunidade
	 */
	public final void setComunidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String comunidade)
	{
		getMendixObject().setValue(context, MemberNames.Comunidade.toString(), comunidade);
	}

	/**
	 * @return value of Ano_Talhao
	 */
	public final java.lang.Integer getAno_Talhao()
	{
		return getAno_Talhao(getContext());
	}

	/**
	 * @param context
	 * @return value of Ano_Talhao
	 */
	public final java.lang.Integer getAno_Talhao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Ano_Talhao.toString());
	}

	/**
	 * Set value of Ano_Talhao
	 * @param ano_talhao
	 */
	public final void setAno_Talhao(java.lang.Integer ano_talhao)
	{
		setAno_Talhao(getContext(), ano_talhao);
	}

	/**
	 * Set value of Ano_Talhao
	 * @param context
	 * @param ano_talhao
	 */
	public final void setAno_Talhao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ano_talhao)
	{
		getMendixObject().setValue(context, MemberNames.Ano_Talhao.toString(), ano_talhao);
	}

	/**
	 * @return value of Numero_talhao
	 */
	public final java.lang.Integer getNumero_talhao()
	{
		return getNumero_talhao(getContext());
	}

	/**
	 * @param context
	 * @return value of Numero_talhao
	 */
	public final java.lang.Integer getNumero_talhao(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Numero_talhao.toString());
	}

	/**
	 * Set value of Numero_talhao
	 * @param numero_talhao
	 */
	public final void setNumero_talhao(java.lang.Integer numero_talhao)
	{
		setNumero_talhao(getContext(), numero_talhao);
	}

	/**
	 * Set value of Numero_talhao
	 * @param context
	 * @param numero_talhao
	 */
	public final void setNumero_talhao(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numero_talhao)
	{
		getMendixObject().setValue(context, MemberNames.Numero_talhao.toString(), numero_talhao);
	}

	/**
	 * @return value of Orientacoes
	 */
	public final java.lang.Boolean getOrientacoes()
	{
		return getOrientacoes(getContext());
	}

	/**
	 * @param context
	 * @return value of Orientacoes
	 */
	public final java.lang.Boolean getOrientacoes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Orientacoes.toString());
	}

	/**
	 * Set value of Orientacoes
	 * @param orientacoes
	 */
	public final void setOrientacoes(java.lang.Boolean orientacoes)
	{
		setOrientacoes(getContext(), orientacoes);
	}

	/**
	 * Set value of Orientacoes
	 * @param context
	 * @param orientacoes
	 */
	public final void setOrientacoes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean orientacoes)
	{
		getMendixObject().setValue(context, MemberNames.Orientacoes.toString(), orientacoes);
	}

	/**
	 * @return value of Tipo
	 */
	public final java.lang.String getTipo()
	{
		return getTipo(getContext());
	}

	/**
	 * @param context
	 * @return value of Tipo
	 */
	public final java.lang.String getTipo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tipo.toString());
	}

	/**
	 * Set value of Tipo
	 * @param tipo
	 */
	public final void setTipo(java.lang.String tipo)
	{
		setTipo(getContext(), tipo);
	}

	/**
	 * Set value of Tipo
	 * @param context
	 * @param tipo
	 */
	public final void setTipo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tipo)
	{
		getMendixObject().setValue(context, MemberNames.Tipo.toString(), tipo);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return ficha_MensalMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.Ficha_Mensal that = (nativemobile.proxies.Ficha_Mensal) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
