// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobile.proxies;

public class lista_de_objetivos_Mensal implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject lista_de_objetivos_MensalMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NativeMobile.lista_de_objetivos_Mensal";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		objetivo("objetivo"),
		Feito("Feito");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public lista_de_objetivos_Mensal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected lista_de_objetivos_Mensal(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject lista_de_objetivos_MensalMendixObject)
	{
		if (lista_de_objetivos_MensalMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, lista_de_objetivos_MensalMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.lista_de_objetivos_MensalMendixObject = lista_de_objetivos_MensalMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static nativemobile.proxies.lista_de_objetivos_Mensal initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nativemobile.proxies.lista_de_objetivos_Mensal(context, mendixObject);
	}

	public static nativemobile.proxies.lista_de_objetivos_Mensal load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nativemobile.proxies.lista_de_objetivos_Mensal.initialize(context, mendixObject);
	}

	public static java.util.List<nativemobile.proxies.lista_de_objetivos_Mensal> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> nativemobile.proxies.lista_de_objetivos_Mensal.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of objetivo
	 */
	public final java.lang.String getobjetivo()
	{
		return getobjetivo(getContext());
	}

	/**
	 * @param context
	 * @return value of objetivo
	 */
	public final java.lang.String getobjetivo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.objetivo.toString());
	}

	/**
	 * Set value of objetivo
	 * @param objetivo
	 */
	public final void setobjetivo(java.lang.String objetivo)
	{
		setobjetivo(getContext(), objetivo);
	}

	/**
	 * Set value of objetivo
	 * @param context
	 * @param objetivo
	 */
	public final void setobjetivo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String objetivo)
	{
		getMendixObject().setValue(context, MemberNames.objetivo.toString(), objetivo);
	}

	/**
	 * @return value of Feito
	 */
	public final java.lang.Boolean getFeito()
	{
		return getFeito(getContext());
	}

	/**
	 * @param context
	 * @return value of Feito
	 */
	public final java.lang.Boolean getFeito(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Feito.toString());
	}

	/**
	 * Set value of Feito
	 * @param feito
	 */
	public final void setFeito(java.lang.Boolean feito)
	{
		setFeito(getContext(), feito);
	}

	/**
	 * Set value of Feito
	 * @param context
	 * @param feito
	 */
	public final void setFeito(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean feito)
	{
		getMendixObject().setValue(context, MemberNames.Feito.toString(), feito);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return lista_de_objetivos_MensalMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nativemobile.proxies.lista_de_objetivos_Mensal that = (nativemobile.proxies.lista_de_objetivos_Mensal) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
